---
title: "SOCC Experiments"
author: "David Ferreira Quaresma (david.quaresma@ccc.ufcg.edu.br)"
date: "May, 2019"
output: pdf_document
---

```{r}
require(dplyr)
require(ggplot2)
require(quantileCI)

print_summary_table <- function(runtime_language, nogci, gci, zero) {
  nogcireq <- (nogci %>% filter(status == 200))$request_time
  nogcierr <- NROW(nogci %>% filter(status != 200))
  gcireq <- (gci %>% filter(status == 200))$request_time
  gcierr <- NROW(gci %>% filter(status != 200))
  zeroreq <- (zero %>% filter(status == 200))$request_time
  zeroerr <- NROW(zero %>% filter(status != 200))
  cat("#fail:", paste(runtime_language, "NG:", sep=""), nogcierr, " | ",
      paste(runtime_language, "G:", sep=""), gcierr, " | ",
      paste(runtime_language, "ZC:", sep=""), zeroerr,  "\n")
  cat("#req: ", paste(runtime_language, "NG:", sep=""), NROW(nogcireq), " | ",
      paste(runtime_language, "G:", sep=""), NROW(gcireq), " | ",
      paste(runtime_language, "ZC:", sep=""), NROW(zeroreq), "\n")
  stats <- function(df, tag) {
    p50 = quantileCI::quantile_confint_nyblom(df, 0.5)
    p95 = quantileCI::quantile_confint_nyblom(df, 0.95)
    p99 = quantileCI::quantile_confint_nyblom(df, 0.99)
    p999 = quantileCI::quantile_confint_nyblom(df, 0.999)
    p9999 = quantileCI::quantile_confint_nyblom(df, 0.9999)
    
    cat("Latency(ms) ", tag, " ")
    cat("avg:", signif(t.test(df)$conf.int, digits = 2), " | ")
    cat("50:", signif(p50, digits = 4), " | ")
    cat("95:", signif(p95, digits = 4), " | ")
    cat("99:", signif(p99, digits = 4), " | ")
    cat("99.9:", signif(p999, digits = 4), " | ")
    cat("99.99:", signif(p9999, digits = 4), " | ")
    cat("Dist.Tail.:", signif(p9999-p50, digits = 4))
    cat("\n")
  }
  stats(nogcireq, paste(runtime_language, "NG", sep=""))
  stats(gcireq, paste(runtime_language, "G ", sep=""))
  stats(zeroreq, paste(runtime_language, "ZC", sep=""))
}

path <- "./results/"

read.al <- function(runtime_language, type, expid) {
  p <- paste(path, runtime_language, type, "-NGINX-access-e", expid, ".log", sep="")
  df <- read.csv(p, sep=";",header=T, dec=".")
  df$request_time <- df$request_time * 1000
  return(tail(df, -100))
}

gci <- rbind(
  read.al("go", "gci", "1"),
  read.al("go", "gci", "2"),
  read.al("go", "gci", "3")
)

nogci <- rbind(
  read.al("go", "nogci", "1"),
  read.al("go", "nogci", "2"),
  read.al("go", "nogci", "3")
)

zero <- rbind(
  read.al("go", "zero", "1"),
  read.al("go", "zero", "2"),
  read.al("go", "zero", "3")
)
```
# Table: Go Experiment
```{r}
print_summary_table("go", nogci,  gci, zero)
```
